### ISSUE TITLE
Unexpected count getting in from the counter

### ISSUE THREAD

**Issue by maxmithun** [CommBank/ebenezer#126] opened 2015-11-10 05:52 UTC
While writing the data from a TypedPipe to a disk we are getting a count more that the records written.

The count seems to be exactly double or near to it. The pipe used for writing is created by a left joining 2 pipes 

the code used to write the records is mentioned below

```
 pipe.writeExecution(ParquetScroogeSource[T](config.output))
      .getAndResetCounters
      .map { case (_, counters) => counters.get(StatKeys.tuplesWritten).getOrElse(0) }

```

(Rowan: edited `PartitionParquetScroogeSource` -> `ParquetScroogeSource`)

**Comment by stephanh** [comment] 2015-11-10 06:15
Can you consistently reproduce this problem?

**Comment by maxmithun** [comment] 2015-11-10 11:08
Yes! We are getting this count everytime with CLM

**Comment by stephanh** [comment] 2015-11-10 22:24
Can you please create a test case that reproduces this.

**Comment by maxmithun** [comment] 2015-11-11 09:09
I have created  the test case for that. I will update it accordingly using minimal steps

**Comment by rowandavies** [comment] 2015-11-18 23:47
@maxmithun Just checking where you got to with the test case.  If you want an easy way of writing a minimal program, I'd suggest following the ebenezer examples.  You could even make your bug-reproduction a new ebenezer example in a branch.  Let me know if I can help.

**Comment by maxmithun** [comment] 2015-11-19 01:56
I have reproduce issue with an example in maestro. But didn't get time to work on it and make it a minimal dependency test case or the one in ebenezer.

**Comment by vineethvarghese** [comment] 2015-11-26 22:15
@maxmithun Do we have a test for this? If these counts are critical for your release (it could be critical for others too if not you), it is critical that we get that test case. 

@anandsiva What can we do to help @maxmithun get this test case out?

**Comment by anandsiva** [comment] 2015-11-26 23:13
@vineethvarghese I have spoken to @maxmithun  about this and he said he would be uploading the test case. @maxmithun Please call out if you have any dependencies.

**Comment by rowandavies** [comment] 2015-11-27 05:51
@maxmithun Looking at the farlo-clm, I guess that the actual code doesn't use `PartitionParquetScroogeSource` but `ParquetScroogeSource` instead?

**Comment by maxmithun** [comment] 2015-11-27 05:55
Yes its using 'ParquetScroogeSource' . Do we have any reported issue using 'ParquetScroogeSource'

**Comment by rowandavies** [comment] 2015-11-27 06:38
There's no specifically relevant issues for 'ParquetScroogeSource'.  I've edited this issue just to avoid confusion.

**Comment by maxmithun** [comment] 2015-12-01 01:59
@rowandavies @stephanh I have send the screen shots and logs of the job executed in cluster , which has the count mismatch. 

The counter `tupleswritten` of the last mapreduce job is showing the correct value which is expected. but what we are getting is the value which in counter `tuplesread`. 

 
count of the record1 used for join : 1611779
count of the record2 used to join : 4 
count obtained from counter `tuples written` : 1611783 
count of record in wriiten location: 4

**Comment by vineethvarghese** [comment] 2015-12-01 08:21
Is this reproducible in a test case?

On Tuesday, December 1, 2015, Mithun Antony <notifications@github.com>
wrote:

> @rowandavies <https://github.com/rowandavies> @stephanh
> <https://github.com/stephanh> I have send the screen shots and logs of
> the job executed in cluster , which has the count mismatch.
>
> The counter tupleswritten of the last mapreduce job is showing the
> correct value which is expected. but what we are getting is the value which
> in counter tuplesread.
>
> count of the record1 used for join : 1611779
> count of the record2 used to join : 4
> count obtained from counter tuples written : 1611783
> count of record in wriiten location: 4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CommBank/ebenezer/issues/126#issuecomment-160823589>.
>


-- 
-V

**Comment by maxmithun** [comment] 2015-12-01 10:30
Issue was not reproduce. The one I be shown as reproduced was not the exact scenario. 

@rowandavies can you please forward the logs to @vineethvarghese too

**Comment by vineethvarghese** [comment] 2015-12-01 21:52
Do you mean you can't reproduce it in the test case but on the cluster it
happens consistently? Or is it that it doesn't happen consistently even on
the cluster?

**Comment by rowandavies** [comment] 2015-12-03 04:06
@MinuMichaelOlassayil @sintokitteera @aswinrkrishnan Does this issue occur with local testing with farlo-clm or just on the cluster?

**Comment by MinuMichaelOlassayil** [comment] 2015-12-03 05:05
Both local test as well as test in cluster has this issue.

**Comment by vineethvarghese** [comment] 2015-12-04 02:08
@maxmithun mentioned that it wasn't reproducible in unit tests. So, if it is reproducible in unit tests, please share a test case.

**Comment by sintokitteera** [comment] 2015-12-09 03:54
@rowandavies @vineethvarghese I have uploaded the CLM unit test which reproduces the issue in Stash and sent the link via mail.

**Comment by rowandavies** [comment] 2015-12-17 05:04
Okay, I eventually managed to reproduce this with some minimal code based on what was provided. The full (pure scalding) program is below.

Note that developers should generally aim to provide similarly minimal code to reproduce issues.  If assistance is required to do this in some cases, that's fine, but over time we should all be learning how to do such things.

```
import com.twitter.scalding.{Config, Execution, TypedPipe, ExecutionApp, StatKey}

import cascading.flow.StepCounters

object TestCounterBug extends ExecutionApp {
  val tuplesWritten = StatKey(StepCounters.Tuples_Written.toString, "cascading.flow.StepCounters")
  def job: Execution[Unit] = for {
      _     <- Execution.from(())
      pipe   = TypedPipe.from(List(1))
                 .groupBy(_ => ()).maxBy(_ => ()).values
                 .groupBy(_ => ()).maxBy(_ => ()).values
                 .groupBy(_ => ()).maxBy(_ => ()).values
      count <- pipe.debug       //  `debug` to show the actual tuples count
                 .toIterableExecution
                 .getAndResetCounters
                 .map { case (_, counters) => counters.get(tuplesWritten).getOrElse(0) }
      _     <- Execution.from(println(s"\ntuplesWritten: ${count}\n"))
  } yield ()
}
```

Based on experimenting with variations of this, and looking through the code for scalding and cascading, it seems that `cascading.flow.StepCounters.Tuples_Written` actually sums up the counts of the tuples output by the individual cascading steps in a cascading flow.  Each groupBy will be in a separate step, so the final summed count includes the tuples output by those and input to the next step.

So, fetching this counter isn't what you want here.  There's no bug in Ebenezer involved, but it's clear you've followed what Maestro does in `view` and `viewHive` so those have a similar issue to your code and will need to be fixed.

**Comment by rowandavies** [comment] 2016-01-14 02:05
I've raised https://github.com/twitter/scalding/issues/1461 related to this.

Meanwhile I've swapped to using a separate counter in the maestro code for `view` and `viewHive`:  https://github.com/CommBank/maestro/pull/469 and opened a new issue https://github.com/CommBank/maestro/issues/475 related to swapping back to the cascading counter if scalding supports this in future.

@maxmithun For your specific issue, you should be able to swap to using `view` instead of calling `writeExecution` directly.  (If not, and it seems appropriate, you can reopen this issue.)

**Closed by rowandavies** 2016-01-14 02:05 UTC
Labels: bug
