### ISSUE TITLE
Parquet reading throws ParquetDecodingException . 

### ISSUE THREAD

**Issue by Vidhyaparvathy** [CommBank/ebenezer#93] opened 2015-03-24 01:30 UTC
We were trying to find the delta between two tables which has similar column names . One table had data in text ( a table from default) and the other had it in parquet (table from pr). The parquet table  was the result of an old maestro job which does not have any "optional" or "required"  in the thrift .  When we ran the job it showed an error like , required binary "columnname" cannot be converted to optional binary  "columnname ". We tried specifying all columns as "required" in the thrift and ran it again . Got the same error . Tried running with "optional" in thrift , and got the same error . 
```
at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:189)
    at parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:130)
    at parquet.hadoop.mapred.DeprecatedParquetInputFormat$RecordReaderWrapper.<init>(DeprecatedParquetInputFormat.java:94)
    at parquet.hadoop.mapred.DeprecatedParquetInputFormat.getRecordReader(DeprecatedParquetInputFormat.java:47)
    at cascading.tap.hadoop.io.MultiInputFormat$1.operate(MultiInputFormat.java:253)
    at cascading.tap.hadoop.io.MultiInputFormat$1.operate(MultiInputFormat.java:248)
    at cascading.util.Util.retry(Util.java:762)
    at cascading.tap.hadoop.io.MultiInputFormat.getRecordReader(MultiInputFormat.java:247)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:394)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.NullPointerException
    at parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:264)
    at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:60)
    at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:74)
    at parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:110)
    at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:174)
    ... 14 more
2015-03-24 10:24:06,252 INFO org.apache.hadoop.mapred.TaskLogsTruncater: Initializing logs' truncater with mapRetainSize=-1 and reduceRetainSize=-1
2015-03-24 10:24:06,255 WARN org.apache.hadoop.mapred.Child: Error running child
parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file 
    at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:189)
    at parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:130)
    at parquet.hadoop.mapred.DeprecatedParquetInputFormat$RecordReaderWrapper.<init>(DeprecatedParquetInputFormat.java:94)
    at parquet.hadoop.mapred.DeprecatedParquetInputFormat.getRecordReader(DeprecatedParquetInputFormat.java:47)
    at cascading.tap.hadoop.io.MultiInputFormat$1.operate(MultiInputFormat.java:253)
    at cascading.tap.hadoop.io.MultiInputFormat$1.operate(MultiInputFormat.java:248)
    at cascading.util.Util.retry(Util.java:762)
    at cascading.tap.hadoop.io.MultiInputFormat.getRecordReader(MultiInputFormat.java:247)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:394)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.NullPointerException
    at parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:264)
    at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:60)
    at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:74)
    at parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:110)
    at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:174)
    ... 14 more
2015-03-24 10:24:06,259 INFO org.apache.hadoop.mapred.Task: Runnning cleanup for the task
```

**Comment by stephanh** [comment] 2015-03-24 04:24
Can you please provide some more details. It is very hard to understand what the problem is and what you need.

Also for exceptions it would be good if you can enclose them in ``` to make it easier to read.

**Comment by vineethMM** [comment] 2015-03-25 00:04
Hi, 
I got the same exception while reading parquet files. 
Here are the details.
  1. The parquet files are written by Hive partitioned table (CDH5.2.4). 
  2. Trying to read those files using ParquetScroogeSource (au.com.cba.omnia.ebenezer.scrooge.ParquetScroogeSource) from Ebenezer using a thrift structure.
 3. Thrift has more than 150 columns and all of them are of type String and are required. 
 4.  The read operation is a part of scalding Execution work flow.
 5. Attaching the screen shot of task tracker log file (job id 'job_201503212127_7731'). 
![screen shot 2015-03-25 at 10 49 25 am](https://cloud.githubusercontent.com/assets/11322952/6815517/b230a828-d2de-11e4-857e-99a57d829140.png)

**Comment by rowandavies** [comment] 2015-03-30 08:05
@vineethMM That screenshot is hard to read on the screen without opening it, and hard to automatically compare with the first exception.  Can you just post the text, with with ``` on a line by itself above it, and another line with just ``` below it?

**Comment by rowandavies** [comment] 2015-03-31 07:56
@Vidhyaparvathy @vineethMM Investigating this issue will require a minimal version of your code that produces the exception, preferably as a branch on stash, and any files required, like the old parquet file.

**Comment by vineethMM** [comment] 2015-04-01 22:32
@rowandavies  I had some experiments with this error. I was able to solve the issue by changing the thrift structure, from required filed to optional field. I am not sure, whether this is the right fix, since the files are written by a thrift where all the fields were marked as required.

**Comment by rowandavies** [comment] 2015-04-07 08:21
@vineethMM Okay, that's good to know.  I still haven't seen any of the code that leads to this error, so there's not much I can do in terms of investigating it at this point.  Can you please make your code available in a branch in a stash repo that I can access?  @Vidhyaparvathy Can you do similarly?

**Comment by rowandavies** [comment] 2015-04-08 07:34
From an email from @vineethMM:
> As I mentioned earlier, had some experiments with this. And now I doubt is it really an issue or its a expected behaviour. 
> Please  find the code repo link
> https://stash.odp.cba/users/manayivi/repos/manayivi-etl.records-fundflow/browse
>
> The branch 'decode-issue’ has minimal code to recreate the scenario. Please find the test cases where both the running version and error version are included.

**Comment by rowandavies** [comment] 2015-04-08 07:44
@vineethMM I eventually managed to get that code to run and produce an exception.  

For future reference, payment_journal_stag is an empty directory hence not stored by git.  Also, it's always good to test a branch you're providing by checking out a fresh copy.

Having seen the exception, it's not clear to me that it's the same as the first one you posted.  Can you provide a version that directly produces the same exception?  Or, is this no longer an issue - if so, we should close it.

Regardless, this bug is unlikely to be fixed during this sprint.

**Comment by vineethMM** [comment] 2015-04-08 08:25
Am not sure whether your are running the test suite, if yes that will mask the exception message. The same exception can be recreated if we run the code as a jar.

**Comment by rowandavies** [comment] 2015-04-09 22:54
Okay, can you tell me exactly how to reproduce the exception?  It's quite inefficient for me to keep guessing and finding that I'm not doing the same thing that you are.

**Comment by rowandavies** [comment] 2015-04-12 23:00
I'm closing this issue since it appears that the behaviour is what's expected rather than due to a bug.  Should other situations arise where similar behaviour seems due to a bug, we can reopen this issue or open a new one as seems appropriate.

**Comment by Fantoccini** [comment] 2015-08-06 06:58
Hi, I encountered this error as well.

I'm trying to read data from hive table pr_hls.loan_master_szlnmst, on hdfs, the paths are:
`/prod/view/warehouse/HLS/LOAN_MASTER_SZLNMST/year=*/month=*/day=*`

using following code:

`newLMPPipe                = { if (newLMP.length > 0) ParquetScroogeSource[LoanMasterSzlnmst](newLMP:_ *) else TypedPipe.empty }: TypedPipe[LoanMasterSzlnmst]`

I've put my code on `dn01` in `/temp_disk1/home/zhuti-adm/dataproducts.features-personalloancollection`

The parquet file has 241 fields, and there are around 600 files to read.

The error logs are:
```
...
  2015-08-06 15:24:30,856 INFO org.apache.hadoop.mapred.MapTask: Processing split: cascading.tap.hadoop.io.MultiInputSplit@3fd2b246
  2015-08-06 15:24:31,713 WARN cascading.tap.hadoop.io.MultiInputFormat: unable to get record reader, but not retrying
  parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file hdfs://nameservice1/prod/view/warehouse/HLS/LOAN_MASTER_SZLNMST/year=2015/month=07/day=06/part-1436198627511-00000-00000-m-00000.parquet
  at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:216)
  at parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:144)
  at parquet.hadoop.mapred.DeprecatedParquetInputFormat$RecordReaderWrapper.<init>(DeprecatedParquetInputFormat.java:91)
...
```

I was thinking it's a data issue, but if you run:
```
parquet-tools meta hdfs://r01hn01.nw-omnia.cba:8020/prod/view/warehouse/HLS/LOAN_MASTER_SZLNMST/year=2015/month=08/day=04/part-00001-00000-m-00001.parquet
parquet-tools cat hdfs://r01hn01.nw-omnia.cba:8020/prod/view/warehouse/HLS/LOAN_MASTER_SZLNMST/year=2015/month=08/day=04/part-00001-00000-m-00001.parquet
```
the outputs looks good to me, to re-produce this issue, run
```
cd /temp_disk1/home/zhuti-adm/dataproducts.features-personalloancollection/target/scala-2.11
HADOOP_CLASSPATH=$(pwd)/dataproducts-features-personalloancollections-assembly-0.0.1-20150806064055-11718af-SNAPSHOT.jar:$HADOOP_CLASSPATH hadoop jar dataproducts-features-personalloancollections-assembly-0.0.1-20150806064055-11718af-SNAPSHOT.jar au.com.cba.omnia.dataproducts.features.personalloancollections.PlcFeatureExecution --hdfs --outputPath /$ENV/view/warehouse/features/personal_loan_collection --db-derive-prefix $OMNIA_HIVE_DB_DERIVE_PREFIX --hdfs-root /user/zhuti-adm
```

the related load data job will fail, you can find the error log from job tracker -> task -> syslog.

**Comment by stephanh** [comment] 2015-08-07 04:51
In the chat you mentioned that it only fails for some files?

Can you please use the meta command to compare the schemas in a working and not working file, in particular check that the optionality for all the fields is the same in both files.

**Comment by Fantoccini** [comment] 2015-08-07 05:13
I thought it only failed on some file, so I tried to remove those files in load code on each run. After I removed 6 'bad' files, the M/R job still crashed on another file.

I wrote a shell script run parquet-tools `head`, `schema` and `meta` on all loan master files, no error found.

I can't find low level parquet code related to this issue in ebenezer, I suspect the error comes from outdated parquet code in CDH jar.

**Comment by stephanh** [comment] 2015-08-07 05:20
@afcowie we don't really have the bandwidth to investigate this. Can your team help @Fantoccini investigate this?

**Comment by Fantoccini** [comment] 2015-08-10 03:46
update: I copied the file from hdfs to local disk, run with --local and the same code, everything works fine.

**Comment by Fantoccini** [comment] 2015-08-12 01:11
Update: it might be:
data schema inconsistent + outdated code in jar + cluster settings
will attach a remote debugger on cluster and see if I can find the root cause.

**Comment by Fantoccini** [comment] 2015-08-19 01:06
Update: it's a data schema inconsistent issue, has informed the data team.

**Closed by Fantoccini** 2015-08-19 01:06 UTC

**Comment by stephanh** [comment] 2015-08-19 01:18
Great. Thank you @Fantoccini
